version: 25
jobs:
- name: Build and Publish
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run Tests
    runInContainer: true
    image: node:18-alpine
    interpreter: !DefaultInterpreter
      commands:
      - set -o errexit
      # TODO(ndhoule): Use this to warm build cache?
      - yarn install --immutable
      - yarn run lint
      - yarn run typecheck
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: Build and Publish Image
    tags: ndhoule/nathanhoule.com:latest ndhoule/nathanhoule.com:@commit_hash@
    publish: true
    removeDanglingImages: true
    moreOptions: --build-arg NEXT_PUBLIC_MAPTILER_API_KEY=@secret:maptiler_api_key@
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Deploy
    runInContainer: true
    image: hashicorp/nomad
    interpreter: !DefaultInterpreter
      commands:
      # XXX(ndhoule): Nomad uses busybox as a base image, which doesn''t bundle OpenSSL.
      # Consequently, many TLS-encrypted requests fail.
      - NOMAD_SKIP_VERIFY=1 NOMAD_ADDR="@property:nomad_addr@" IMAGE_TAG="@commit_hash@" scripts/deploy.sh
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
