script: make
deploy:
  provider: s3
  local-dir: build
  bucket: nathanhoule.com
  endpoint: nathanhoule.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  on:
    branch: master
  skip_cleanup: true
  access_key_id:
    secure: H9VtNToNKASiF/I3JRex+IOJNChrnrsnt6oI2bQ434dZstmfYj21u1Gq2YdNv07FLr5+PxHFcoHd/WPVVRKNy7MFxxiaIIOGtJIVc8I/4loGlWrjQjA3KEJXMthlBEdgkOjnhnUB/83V+EZcnGxVj5qXvFXAJWEpbQZlNw1+lSY=""
  secret_access_key:
    secure: Fo4CinM9gngGo+/wxKO4jN4OKxESI6Fd5dewE8QCUUvqKMyqSFKAq7cridHI5/PJcg4ROp8n+x2tFdnYehf7NAcHqv9a3fRLBoOBMQznsMn7MZOUK0i6ck61NNSIJNWzB8wbO3I4pyqi6AS8W3MDosi3O0yONg94ugcR3mWeVfw=
